/* Generated by re2c 0.13.5 on Fri Apr 10 01:08:43 2015 */
#line 1 "sql_lex.l"
#include <string>
#include <vector>
#include <iostream>
#include "sql_desc.h"
#include "sql_yacc.hpp"
#include "lex_global.h"

Scanner global_scanner;

#define YYCTYPE char
#define YYFILL(n)
#define GS(t) global_scanner.t

#define STATE(name) yyc##name
#define BEGIN(name) YYSETCONDITION(STATE(name))
#define YYCURSOR GS(yy_cursor)
#define YYLIMIT GS(yy_limit)
#define YYMARKER GS(yy_marker)
#define yytext ((char *)GS(yy_text))
#define yyleng GS(yy_leng)

#define SAVE_TOKEN do {yyleng = YYCURSOR - yytext; yylval.lex_string = new std::string(yytext, yyleng); }while(0)
int scan(){
  for(;;){
  GS(yy_text) = YYCURSOR;
  
#line 30 "sql_lex.cpp"
{
	YYCTYPE yych;

	if ((YYLIMIT - YYCURSOR) < 19) YYFILL(19);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy57;
	case '\t':
	case ' ':	goto yy50;
	case '!':	goto yy5;
	case '&':	goto yy11;
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case ';':	goto yy3;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy43;
	case '<':	goto yy12;
	case '=':	goto yy9;
	case '>':	goto yy14;
	case 'A':	goto yy31;
	case 'B':	goto yy37;
	case 'C':	goto yy52;
	case 'D':	goto yy23;
	case 'E':
	case 'J':
	case 'K':
	case 'P':
	case 'Q':
	case 'R':
	case 'V':
	case 'X':
	case 'Y':
	case 'Z':	goto yy54;
	case 'F':	goto yy21;
	case 'G':	goto yy35;
	case 'H':	goto yy39;
	case 'I':	goto yy19;
	case 'L':	goto yy25;
	case 'M':	goto yy27;
	case 'N':	goto yy48;
	case 'O':	goto yy41;
	case 'S':	goto yy16;
	case 'T':	goto yy46;
	case 'U':	goto yy29;
	case 'W':	goto yy33;
	case 'a':	goto yy32;
	case 'b':	goto yy38;
	case 'c':	goto yy53;
	case 'd':	goto yy24;
	case 'e':
	case 'j':
	case 'k':
	case 'p':
	case 'q':
	case 'r':
	case 'v':
	case 'x':
	case 'y':
	case 'z':	goto yy56;
	case 'f':	goto yy22;
	case 'g':	goto yy36;
	case 'h':	goto yy40;
	case 'i':	goto yy20;
	case 'l':	goto yy26;
	case 'm':	goto yy28;
	case 'n':	goto yy49;
	case 'o':	goto yy42;
	case 's':	goto yy18;
	case 't':	goto yy47;
	case 'u':	goto yy30;
	case 'w':	goto yy34;
	case '|':	goto yy7;
	default:	goto yy2;
	}
yy2:
	YYCURSOR = YYMARKER;
	goto yy17;
yy3:
	++YYCURSOR;
#line 27 "sql_lex.l"
	{return yytext[0];}
#line 123 "sql_lex.cpp"
yy5:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy327;
	default:	goto yy6;
	}
yy6:
#line 28 "sql_lex.l"
	{return NOT2_SYM;}
#line 133 "sql_lex.cpp"
yy7:
	++YYCURSOR;
#line 29 "sql_lex.l"
	{return OR2_SYM;}
#line 138 "sql_lex.cpp"
yy9:
	++YYCURSOR;
#line 30 "sql_lex.l"
	{return EQ;}
#line 143 "sql_lex.cpp"
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
	case '&':	goto yy325;
	default:	goto yy2;
	}
yy12:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '<':	goto yy319;
	case '=':	goto yy317;
	case '>':	goto yy321;
	default:	goto yy13;
	}
yy13:
#line 32 "sql_lex.l"
	{return LT;}
#line 161 "sql_lex.cpp"
yy14:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy315;
	case '>':	goto yy313;
	default:	goto yy15;
	}
yy15:
#line 37 "sql_lex.l"
	{return GT_SYM;}
#line 172 "sql_lex.cpp"
yy16:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'E':
	case 'e':	goto yy220;
	case 'H':
	case 'h':	goto yy221;
	case 'Q':
	case 'q':	goto yy222;
	case 'T':
	case 't':	goto yy223;
	default:	goto yy55;
	}
yy17:
#line 90 "sql_lex.l"
	{SAVE_TOKEN; return IDENT;}
#line 189 "sql_lex.cpp"
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy220;
	case 'H':
	case 'h':	goto yy221;
	case 'Q':
	case 'q':	goto yy222;
	case 'T':
	case 't':	goto yy223;
	default:	goto yy55;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy211;
	case 'S':
	case 's':	goto yy213;
	default:	goto yy55;
	}
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy211;
	case 'S':
	case 's':	goto yy213;
	default:	goto yy55;
	}
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy199;
	case 'O':
	case 'o':	goto yy200;
	case 'R':
	case 'r':	goto yy201;
	default:	goto yy55;
	}
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy199;
	case 'O':
	case 'o':	goto yy200;
	case 'R':
	case 'r':	goto yy201;
	default:	goto yy55;
	}
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy188;
	case 'U':
	case 'u':	goto yy189;
	default:	goto yy55;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy188;
	case 'U':
	case 'u':	goto yy189;
	default:	goto yy55;
	}
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy179;
	case 'O':
	case 'o':	goto yy180;
	default:	goto yy55;
	}
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy179;
	case 'O':
	case 'o':	goto yy180;
	default:	goto yy55;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy175;
	default:	goto yy55;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy175;
	default:	goto yy55;
	}
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy162;
	case 'P':
	case 'p':	goto yy163;
	default:	goto yy55;
	}
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy162;
	case 'P':
	case 'p':	goto yy163;
	default:	goto yy55;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy150;
	case 'N':
	case 'n':	goto yy151;
	case 'S':
	case 's':	goto yy152;
	default:	goto yy55;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy150;
	case 'N':
	case 'n':	goto yy151;
	case 'S':
	case 's':	goto yy152;
	default:	goto yy55;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy145;
	default:	goto yy55;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy145;
	default:	goto yy55;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy140;
	default:	goto yy55;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy140;
	default:	goto yy55;
	}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy124;
	case 'E':
	case 'e':	goto yy125;
	case 'Y':
	case 'y':	goto yy126;
	default:	goto yy55;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy124;
	case 'E':
	case 'e':	goto yy125;
	case 'Y':
	case 'y':	goto yy126;
	default:	goto yy55;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy105;
	case 'I':
	case 'i':	goto yy106;
	default:	goto yy55;
	}
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy105;
	case 'I':
	case 'i':	goto yy106;
	default:	goto yy55;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy93;
	case 'R':
	case 'r':	goto yy94;
	default:	goto yy55;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy93;
	case 'R':
	case 'r':	goto yy94;
	default:	goto yy55;
	}
yy43:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy43;
	default:	goto yy45;
	}
yy45:
#line 63 "sql_lex.l"
	{return LONG_NUM;}
#line 439 "sql_lex.cpp"
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy89;
	default:	goto yy55;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy89;
	default:	goto yy55;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy86;
	default:	goto yy55;
	}
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy86;
	default:	goto yy55;
	}
yy50:
	++YYCURSOR;
#line 69 "sql_lex.l"
	{continue;}
#line 472 "sql_lex.cpp"
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy59;
	case 'H':
	case 'h':	goto yy60;
	case 'L':
	case 'l':	goto yy61;
	case 'O':
	case 'o':	goto yy62;
	case 'R':
	case 'r':	goto yy63;
	default:	goto yy55;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy59;
	case 'H':
	case 'h':	goto yy60;
	case 'L':
	case 'l':	goto yy61;
	case 'O':
	case 'o':	goto yy62;
	case 'R':
	case 'r':	goto yy63;
	default:	goto yy55;
	}
yy54:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy55:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy17;
	}
yy56:
	yych = *++YYCURSOR;
	goto yy55;
yy57:
	++YYCURSOR;
#line 92 "sql_lex.l"
	{return END_OF_INPUT;}
#line 580 "sql_lex.cpp"
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy82;
	default:	goto yy55;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy76;
	default:	goto yy55;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy72;
	default:	goto yy55;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy68;
	default:	goto yy55;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy64;
	default:	goto yy55;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case '3':	goto yy65;
	default:	goto yy55;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case '2':	goto yy66;
	default:	goto yy55;
	}
yy66:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy67;
	}
yy67:
#line 86 "sql_lex.l"
	{return CHECKSUM_SYM;}
#line 698 "sql_lex.cpp"
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy69;
	default:	goto yy55;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy70;
	default:	goto yy55;
	}
yy70:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy71;
	}
yy71:
#line 89 "sql_lex.l"
	{return COUNT_SYM;}
#line 783 "sql_lex.cpp"
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy73;
	default:	goto yy55;
	}
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy74;
	default:	goto yy55;
	}
yy74:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy75;
	}
yy75:
#line 87 "sql_lex.l"
	{return CLOSE_SYM;}
#line 868 "sql_lex.cpp"
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy77;
	default:	goto yy55;
	}
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy78;
	default:	goto yy55;
	}
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy79;
	default:	goto yy55;
	}
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy80;
	default:	goto yy55;
	}
yy80:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy81;
	}
yy81:
#line 85 "sql_lex.l"
	{return CHARSET;}
#line 967 "sql_lex.cpp"
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy83;
	default:	goto yy55;
	}
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy84;
	default:	goto yy55;
	}
yy84:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy85;
	}
yy85:
#line 84 "sql_lex.l"
	{return CACHE_SYM;}
#line 1052 "sql_lex.cpp"
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy87;
	default:	goto yy55;
	}
yy87:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy88;
	}
yy88:
#line 67 "sql_lex.l"
	{return NOT_SYM;}
#line 1130 "sql_lex.cpp"
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy90;
	default:	goto yy55;
	}
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy91;
	default:	goto yy55;
	}
yy91:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy92;
	}
yy92:
#line 65 "sql_lex.l"
	{return TRUE_SYM;}
#line 1215 "sql_lex.cpp"
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy100;
	default:	goto yy55;
	}
yy94:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	case 'D':
	case 'd':	goto yy96;
	default:	goto yy95;
	}
yy95:
#line 66 "sql_lex.l"
	{return OR_SYM;}
#line 1293 "sql_lex.cpp"
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy97;
	default:	goto yy55;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy98;
	default:	goto yy55;
	}
yy98:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy99;
	}
yy99:
#line 60 "sql_lex.l"
	{return ORDER_SYM;}
#line 1378 "sql_lex.cpp"
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy101;
	default:	goto yy55;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy102;
	default:	goto yy55;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy103;
	default:	goto yy55;
	}
yy103:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy104;
	}
yy104:
#line 62 "sql_lex.l"
	{return OFFSET_SYM;}
#line 1470 "sql_lex.cpp"
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':
	case 'v':	goto yy119;
	default:	goto yy55;
	}
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy107;
	default:	goto yy55;
	}
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy108;
	default:	goto yy55;
	}
yy108:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '_':	goto yy109;
	default:	goto yy55;
	}
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy110;
	default:	goto yy2;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy111;
	default:	goto yy2;
	}
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy112;
	default:	goto yy2;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy113;
	default:	goto yy2;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy114;
	default:	goto yy2;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy115;
	default:	goto yy2;
	}
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy116;
	default:	goto yy2;
	}
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'Y':
	case 'y':	goto yy117;
	default:	goto yy2;
	}
yy117:
	++YYCURSOR;
#line 73 "sql_lex.l"
	{return HIGH_PRIORITY;}
#line 1558 "sql_lex.cpp"
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy120;
	default:	goto yy55;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy121;
	default:	goto yy55;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy122;
	default:	goto yy55;
	}
yy122:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy123;
	}
yy123:
#line 59 "sql_lex.l"
	{return HAVING;}
#line 1650 "sql_lex.cpp"
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy135;
	default:	goto yy55;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy131;
	default:	goto yy55;
	}
yy126:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	case 'T':
	case 't':	goto yy128;
	default:	goto yy127;
	}
yy127:
#line 58 "sql_lex.l"
	{return BY;}
#line 1735 "sql_lex.cpp"
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy129;
	default:	goto yy55;
	}
yy129:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy130;
	}
yy130:
#line 83 "sql_lex.l"
	{return BYTE_SYM;}
#line 1813 "sql_lex.cpp"
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy132;
	default:	goto yy55;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy133;
	default:	goto yy55;
	}
yy133:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy134;
	}
yy134:
#line 82 "sql_lex.l"
	{return BEGIN_SYM;}
#line 1898 "sql_lex.cpp"
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'K':
	case 'k':	goto yy136;
	default:	goto yy55;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy137;
	default:	goto yy55;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy138;
	default:	goto yy55;
	}
yy138:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy139;
	}
yy139:
#line 81 "sql_lex.l"
	{return BACKUP_SYM;}
#line 1990 "sql_lex.cpp"
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy141;
	default:	goto yy55;
	}
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy142;
	default:	goto yy55;
	}
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy143;
	default:	goto yy55;
	}
yy143:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy144;
	}
yy144:
#line 57 "sql_lex.l"
	{return GROUP_SYM;}
#line 2082 "sql_lex.cpp"
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy146;
	default:	goto yy55;
	}
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy147;
	default:	goto yy55;
	}
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy148;
	default:	goto yy55;
	}
yy148:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy149;
	}
yy149:
#line 56 "sql_lex.l"
	{return WHERE;}
#line 2174 "sql_lex.cpp"
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy160;
	default:	goto yy55;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy158;
	default:	goto yy55;
	}
yy152:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	case 'C':
	case 'c':	goto yy154;
	default:	goto yy153;
	}
yy153:
#line 55 "sql_lex.l"
	{return AS;}
#line 2259 "sql_lex.cpp"
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy155;
	default:	goto yy55;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy156;
	default:	goto yy55;
	}
yy156:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy157;
	}
yy157:
#line 80 "sql_lex.l"
	{return ASCII_SYM;}
#line 2344 "sql_lex.cpp"
yy158:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy159;
	}
yy159:
#line 88 "sql_lex.l"
	{return AND_SYM;}
#line 2415 "sql_lex.cpp"
yy160:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy161;
	}
yy161:
#line 79 "sql_lex.l"
	{return ALL;}
#line 2486 "sql_lex.cpp"
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'K':
	case 'k':	goto yy169;
	default:	goto yy55;
	}
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy164;
	default:	goto yy55;
	}
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy165;
	default:	goto yy55;
	}
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy166;
	default:	goto yy55;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy167;
	default:	goto yy55;
	}
yy167:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy168;
	}
yy168:
#line 54 "sql_lex.l"
	{return UPDATE_SYM;}
#line 2592 "sql_lex.cpp"
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy170;
	default:	goto yy55;
	}
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy171;
	default:	goto yy55;
	}
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'W':
	case 'w':	goto yy172;
	default:	goto yy55;
	}
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy173;
	default:	goto yy55;
	}
yy173:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy174;
	}
yy174:
#line 71 "sql_lex.l"
	{return UNKNOWN_SYM;}
#line 2691 "sql_lex.cpp"
yy175:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy176;
	default:	goto yy55;
	}
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy177;
	default:	goto yy55;
	}
yy177:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy178;
	}
yy178:
#line 53 "sql_lex.l"
	{return MODE_SYM;}
#line 2776 "sql_lex.cpp"
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy184;
	default:	goto yy55;
	}
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy181;
	default:	goto yy55;
	}
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'K':
	case 'k':	goto yy182;
	default:	goto yy55;
	}
yy182:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy183;
	}
yy183:
#line 50 "sql_lex.l"
	{return LOCKS_SYM;}
#line 2868 "sql_lex.cpp"
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy185;
	default:	goto yy55;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy186;
	default:	goto yy55;
	}
yy186:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy187;
	}
yy187:
#line 61 "sql_lex.l"
	{return LIMIT;}
#line 2953 "sql_lex.cpp"
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy193;
	default:	goto yy55;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy190;
	default:	goto yy55;
	}
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy191;
	default:	goto yy55;
	}
yy191:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy192;
	}
yy192:
#line 46 "sql_lex.l"
	{return DUAL_SYM;}
#line 3045 "sql_lex.cpp"
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy194;
	default:	goto yy55;
	}
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'B':
	case 'b':	goto yy195;
	default:	goto yy55;
	}
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy196;
	default:	goto yy55;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy197;
	default:	goto yy55;
	}
yy197:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy198;
	}
yy198:
#line 74 "sql_lex.l"
	{return DISABLE_SYM;}
#line 3144 "sql_lex.cpp"
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy207;
	default:	goto yy55;
	}
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy205;
	default:	goto yy55;
	}
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy202;
	default:	goto yy55;
	}
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy203;
	default:	goto yy55;
	}
yy203:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy204;
	}
yy204:
#line 45 "sql_lex.l"
	{return FROM;}
#line 3243 "sql_lex.cpp"
yy205:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy206;
	}
yy206:
#line 49 "sql_lex.l"
	{return FOR_SYM;}
#line 3314 "sql_lex.cpp"
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy208;
	default:	goto yy55;
	}
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy209;
	default:	goto yy55;
	}
yy209:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy210;
	}
yy210:
#line 70 "sql_lex.l"
	{return FALSE_SYM;}
#line 3399 "sql_lex.cpp"
yy211:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	case 'S':
	case 's':	goto yy215;
	default:	goto yy212;
	}
yy212:
#line 51 "sql_lex.l"
	{return IN_SYM;}
#line 3470 "sql_lex.cpp"
yy213:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy214;
	}
yy214:
#line 68 "sql_lex.l"
	{return IS;}
#line 3541 "sql_lex.cpp"
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy216;
	default:	goto yy55;
	}
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy217;
	default:	goto yy55;
	}
yy217:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy218;
	default:	goto yy55;
	}
yy218:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy219;
	}
yy219:
#line 44 "sql_lex.l"
	{return INSERT;}
#line 3633 "sql_lex.cpp"
yy220:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy308;
	default:	goto yy55;
	}
yy221:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy304;
	default:	goto yy55;
	}
yy222:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy236;
	default:	goto yy55;
	}
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy224;
	default:	goto yy55;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy225;
	default:	goto yy55;
	}
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy226;
	default:	goto yy55;
	}
yy226:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy227;
	default:	goto yy55;
	}
yy227:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy228;
	default:	goto yy55;
	}
yy228:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy229;
	default:	goto yy55;
	}
yy229:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '_':	goto yy230;
	default:	goto yy55;
	}
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'J':
	case 'j':	goto yy231;
	default:	goto yy2;
	}
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy232;
	default:	goto yy2;
	}
yy232:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy233;
	default:	goto yy2;
	}
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy234;
	default:	goto yy2;
	}
yy234:
	++YYCURSOR;
#line 72 "sql_lex.l"
	{return STRAIGHT_JOIN;}
#line 3735 "sql_lex.cpp"
yy236:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '_':	goto yy237;
	default:	goto yy55;
	}
yy237:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'B':
	case 'b':	goto yy241;
	case 'C':
	case 'c':	goto yy239;
	case 'N':
	case 'n':	goto yy238;
	case 'S':
	case 's':	goto yy240;
	default:	goto yy2;
	}
yy238:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy296;
	default:	goto yy2;
	}
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy277;
	default:	goto yy2;
	}
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy265;
	default:	goto yy2;
	}
yy241:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':
	case 'i':	goto yy243;
	case 'U':
	case 'u':	goto yy242;
	default:	goto yy2;
	}
yy242:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy253;
	default:	goto yy2;
	}
yy243:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'G':
	case 'g':	goto yy244;
	default:	goto yy2;
	}
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy245;
	default:	goto yy2;
	}
yy245:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy246;
	default:	goto yy2;
	}
yy246:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy247;
	default:	goto yy2;
	}
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy248;
	default:	goto yy2;
	}
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy249;
	default:	goto yy2;
	}
yy249:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy250;
	default:	goto yy2;
	}
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy251;
	default:	goto yy2;
	}
yy251:
	++YYCURSOR;
#line 76 "sql_lex.l"
	{return SQL_BIG_RESULT;}
#line 3851 "sql_lex.cpp"
yy253:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy254;
	default:	goto yy2;
	}
yy254:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy255;
	default:	goto yy2;
	}
yy255:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy256;
	default:	goto yy2;
	}
yy256:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy257;
	default:	goto yy2;
	}
yy257:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy258;
	default:	goto yy2;
	}
yy258:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy259;
	default:	goto yy2;
	}
yy259:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy260;
	default:	goto yy2;
	}
yy260:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy261;
	default:	goto yy2;
	}
yy261:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy262;
	default:	goto yy2;
	}
yy262:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy263;
	default:	goto yy2;
	}
yy263:
	++YYCURSOR;
#line 77 "sql_lex.l"
	{return SQL_BUFFER_RESULT;}
#line 3925 "sql_lex.cpp"
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy266;
	default:	goto yy2;
	}
yy266:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy267;
	default:	goto yy2;
	}
yy267:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy268;
	default:	goto yy2;
	}
yy268:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy269;
	default:	goto yy2;
	}
yy269:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy270;
	default:	goto yy2;
	}
yy270:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy271;
	default:	goto yy2;
	}
yy271:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy272;
	default:	goto yy2;
	}
yy272:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy273;
	default:	goto yy2;
	}
yy273:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':
	case 'l':	goto yy274;
	default:	goto yy2;
	}
yy274:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy275;
	default:	goto yy2;
	}
yy275:
	++YYCURSOR;
#line 75 "sql_lex.l"
	{return SQL_SMALL_RESULT;}
#line 3999 "sql_lex.cpp"
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy278;
	case 'L':
	case 'l':	goto yy279;
	default:	goto yy2;
	}
yy278:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy293;
	default:	goto yy2;
	}
yy279:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy280;
	default:	goto yy2;
	}
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy281;
	default:	goto yy2;
	}
yy281:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'F':
	case 'f':	goto yy282;
	default:	goto yy2;
	}
yy282:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy283;
	default:	goto yy2;
	}
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy284;
	default:	goto yy2;
	}
yy284:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':
	case 'n':	goto yy285;
	default:	goto yy2;
	}
yy285:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':
	case 'd':	goto yy286;
	default:	goto yy2;
	}
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy287;
	default:	goto yy2;
	}
yy287:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy288;
	default:	goto yy2;
	}
yy288:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':
	case 'o':	goto yy289;
	default:	goto yy2;
	}
yy289:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'W':
	case 'w':	goto yy290;
	default:	goto yy2;
	}
yy290:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':
	case 's':	goto yy291;
	default:	goto yy2;
	}
yy291:
	++YYCURSOR;
#line 78 "sql_lex.l"
	{return SQL_CALC_FOUND_ROWS;}
#line 4102 "sql_lex.cpp"
yy293:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy294;
	default:	goto yy2;
	}
yy294:
	++YYCURSOR;
#line 48 "sql_lex.l"
	{return SQL_CACHE_SYM;}
#line 4114 "sql_lex.cpp"
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy297;
	default:	goto yy2;
	}
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy298;
	default:	goto yy2;
	}
yy298:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':
	case 'a':	goto yy299;
	default:	goto yy2;
	}
yy299:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy300;
	default:	goto yy2;
	}
yy300:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':
	case 'h':	goto yy301;
	default:	goto yy2;
	}
yy301:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy302;
	default:	goto yy2;
	}
yy302:
	++YYCURSOR;
#line 47 "sql_lex.l"
	{return SQL_NO_CACHE_SYM;}
#line 4160 "sql_lex.cpp"
yy304:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':
	case 'r':	goto yy305;
	default:	goto yy55;
	}
yy305:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy306;
	default:	goto yy55;
	}
yy306:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy307;
	}
yy307:
#line 52 "sql_lex.l"
	{return SHARE_SYM;}
#line 4245 "sql_lex.cpp"
yy308:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':
	case 'e':	goto yy309;
	default:	goto yy55;
	}
yy309:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':
	case 'c':	goto yy310;
	default:	goto yy55;
	}
yy310:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':
	case 't':	goto yy311;
	default:	goto yy55;
	}
yy311:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy54;
	default:	goto yy312;
	}
yy312:
#line 43 "sql_lex.l"
	{return SELECT_SYM;}
#line 4337 "sql_lex.cpp"
yy313:
	++YYCURSOR;
#line 40 "sql_lex.l"
	{return SHIFT_RIGHT;}
#line 4342 "sql_lex.cpp"
yy315:
	++YYCURSOR;
#line 38 "sql_lex.l"
	{return GE;}
#line 4347 "sql_lex.cpp"
yy317:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '>':	goto yy323;
	default:	goto yy318;
	}
yy318:
#line 33 "sql_lex.l"
	{return LE;}
#line 4357 "sql_lex.cpp"
yy319:
	++YYCURSOR;
#line 39 "sql_lex.l"
	{return SHIFT_LEFT;}
#line 4362 "sql_lex.cpp"
yy321:
	++YYCURSOR;
#line 34 "sql_lex.l"
	{return NE;}
#line 4367 "sql_lex.cpp"
yy323:
	++YYCURSOR;
#line 41 "sql_lex.l"
	{return EQUAL_SYM;}
#line 4372 "sql_lex.cpp"
yy325:
	++YYCURSOR;
#line 31 "sql_lex.l"
	{return AND_AND_SYM;}
#line 4377 "sql_lex.cpp"
yy327:
	++YYCURSOR;
#line 35 "sql_lex.l"
	{return NE;}
#line 4382 "sql_lex.cpp"
}
#line 93 "sql_lex.l"


  }
return 0;
}

int yylex(){
  if(GS(state) == SCANNER_END) return 0;
  if(GS(yy_cursor) >= GS(yy_limit) || GS(found_semicolon) != NULL){
    GS(state) = SCANNER_END;
    return END_OF_INPUT;
  }
  int token;
  token = scan();
#ifdef SQL_DEBUG
  std::cout << "token lex return is " << token << endl;
#endif
  return token;
}

void scan_buffer(char *str, int len){
  GS(yy_text) =  str;
  GS(yy_limit) = str + len;
  GS(yy_cursor) =  str;
  GS(found_semicolon) = NULL;
  GS(state) = SCANNER_START;
}
